### ISSUE TITLE
No _.deepExtend

### ISSUE THREAD

**Issue by b1rdex** [ovcharik/meteor-getting-started#1]
https://github.com/ovcharik/meteor-getting-started/blob/master/todo-list/server/config/accounts.coffee#L7

**Comment by b1rdex** [comment]
Underscore has no such method and meteor crashes.

**Comment by b1rdex** [comment]
https://github.com/ovcharik/meteor-getting-started/blob/master/todo-list/collections/users.coffee#L56

Another usage.

**Comment by ovcharik** [comment]
I extend Underscore methods here
https://github.com/ovcharik/meteor-getting-started/blob/master/todo-list/lib/underscore.coffee

**Comment by b1rdex** [comment]
This is not metioned anywhere in your articles.
